## Saves a network generated by clingo
## Use: clingo .\Adaptive_Network\Clingo_ANN\create_network.lp | python .\Adaptive_Network\Clingo_ANN\save_network.py -s True -p 4 -f 'randomized'

import argparse


parser = argparse.ArgumentParser()
parser.add_argument('-v', default = False, type = bool,
                    help = "Whether to include neuron values in the output file. (Default = False)")
parser.add_argument('-s', default = True, type = bool,
                    help = "Whether to use scaled integers for weights. (Default = True)")
parser.add_argument('-p', default = 4, type = int,
                    help = "Precision for scaled integers. Can be 4 or 6 for 1e4 or 1e6 respectively. (Default = 4)")
parser.add_argument('-f', default='randomized', type=str,
                    help = "Unique identifier for output file name. (Default = 'randomized')")
args = parser.parse_args()

save_values = args.v
scaled_integer = args.s
precision = args.p
identifier = args.f

# Reading in clingo output
toks_last = None
toks = None
toks_next = input().split()

while not (toks_next and toks_next[0].startswith("OPT") or toks_next[0].startswith("SAT") or toks_next[0].startswith("UNSAT")):
    toks_last = toks
    toks = toks_next
    toks_next = input().split()

# Parsing clingo output into facts and network parameters
if toks_next[0].startswith("OPT") or toks_next[0].startswith("SAT"):
    if toks_next[0].startswith("OPT"):
        toks = toks_last
    
    facts = []
    input_size = None
    hidden_size = None
    num_hidden_layers = None
    output_size = None

    for t in toks:
        if t.startswith("neuron"):
            line = t[7:-1]
            param = line.split(',')
            n_type = param[0]
            layer = int(param[1])
            index = int(param[2])
            if save_values and scaled_integer and len(param) > 3:
                value = f'{int(param[3])}'
            elif save_values and not scaled_integer and len(param) > 3:
                value = f'{str(param[3])}'

            facts.append(f"neuron({n_type}, {layer}, {index}).")
            if save_values and len(param) > 3:
                facts.append(f"neuron({n_type}, {layer}, {index}, {value}).")

        elif t.startswith("edge"):
            line = t[5:-1]
            param = line.split(',')
            source_layer = int(param[0])
            source_index = int(param[1])
            target_layer = int(param[2])
            target_index = int(param[3])
            if scaled_integer:
                weight = f'{int(param[4])}'
            else:
                weight = f'{str(param[4])}'

            facts.append(f"edge({source_layer}, {source_index}, {target_layer}, {target_index}, {weight}).")

        elif t.startswith("input_size"):
            line = t[11:-1]
            input_size = int(line)
            facts.append(f"input_size({input_size}).")

        elif t.startswith("hidden_size"):
            line = t[12:-1]
            hidden_size = int(line)
            facts.append(f"hidden_size({hidden_size}).")

        elif t.startswith("num_hidden_layers"):
            line = t[18:-1]
            num_hidden_layers = int(line)
            facts.append(f"num_hidden_layers({num_hidden_layers}).")

        elif t.startswith("output_size"):
            line = t[12:-1]
            output_size = int(line)
            facts.append(f"output_size({output_size}).")

    # Saving network parameters and facts to .lp file
    if scaled_integer:
        file_name = f"ann_scaled_int_{input_size}i_{hidden_size}h_{num_hidden_layers}n_{output_size}o_{identifier}.lp"
    else:
        file_name = f"ann_float_str_{input_size}i_{hidden_size}h_{num_hidden_layers}n_{output_size}o_{identifier}.lp"

    with open(f"Adaptive_Network/Clingo_ANN/models/{file_name}", "w") as f:
        f.write("\n".join(facts))

# In case of unsatisfiability
elif toks_next[0].startswith("UNSAT"):
    print("No solution found.")